In [98]:
import pandas as pd
from keras.models import Sequential
from keras.layers import *
#Split data
from sklearn.model_selection import train_test_split

In [116]:
df = pd.read_csv("./generated_dataset.csv")

In [117]:
df.head()

x1   x2   x3   x4   x5   x6     y
0  156  793  887  490  870  339  2857
1  666  448  118  693  485  640  1770
2  507  544  613  141  258  106  1957
3  792  385  118  492  922  575  2134
4  603  755  979  700  159  851  2345

In [118]:
X = df.drop(labels=['y'], axis=1).values
Y = df[['y']].values

In [121]:
#Model definition
model = Sequential()
model.add(Dense(16, input_dim=6, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

#Run training
model.fit(
    X_train,
    Y_train,
    epochs=40,    
    shuffle=True,
    verbose=2
)


Epoch 1/40
 - 2s - loss: 86672.1606 - acc: 0.0083
Epoch 2/40
 - 1s - loss: 1072.0396 - acc: 0.0248
Epoch 3/40
 - 1s - loss: 343.5152 - acc: 0.0606
Epoch 4/40
 - 1s - loss: 125.8175 - acc: 0.1140
Epoch 5/40
 - 1s - loss: 52.2875 - acc: 0.2179
Epoch 6/40
 - 1s - loss: 24.0926 - acc: 0.3528
Epoch 7/40
 - 1s - loss: 11.9732 - acc: 0.4456
Epoch 8/40
 - 1s - loss: 6.5054 - acc: 0.4831
Epoch 9/40
 - 1s - loss: 3.5265 - acc: 0.5286
Epoch 10/40
 - 1s - loss: 2.3952 - acc: 0.4940
Epoch 11/40
 - 1s - loss: 1.6648 - acc: 0.5929
Epoch 12/40
 - 1s - loss: 1.1871 - acc: 0.6521
Epoch 13/40
 - 1s - loss: 1.0672 - acc: 0.6265
Epoch 14/40
 - 1s - loss: 0.9182 - acc: 0.6168
Epoch 15/40
 - 1s - loss: 0.8223 - acc: 0.6632
Epoch 16/40
 - 1s - loss: 0.7577 - acc: 0.6136
Epoch 17/40
 - 1s - loss: 0.7662 - acc: 0.6438
Epoch 18/40
 - 1s - loss: 0.8060 - acc: 0.6966
Epoch 19/40
 - 1s - loss: 0.7473 - acc: 0.7308
Epoch 20/40
 - 1s - loss: 0.6047 - acc: 0.7191
Epoch 21/40
 - 1s - loss: 0.6000 - acc: 0.6905
Epoch 22

In [122]:
#Lets test the model error rate
test_error_rate = model.evaluate(X_test, Y_test, verbose=0)
print("The mean squared error (MSE) for the test data set is: {}".format(test_error_rate))

The mean squared error (MSE) for the test data set is: [0.05285646332253236, 0.999]


In [131]:
# Make a prediction with the neural network
X_prediction= pd.DataFrame([{'x1':1,'x2':2,'x3':3,'x4':4,'x5':5,'x6':6}])
print( model.predict(X_prediction) )

[[8.977637]]


In [132]:
# Save the model to disk
model.save("trained_model.h5", include_optimizer=False)

In [101]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 8 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Sex         891 non-null object
Age         714 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Embarked    889 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 62.6+ KB


In [102]:
import numpy as np
sum(np.isnan(titanic['Age']))

177

In [103]:
titanic['Age'] = titanic['Age'].fillna(value=titanic['Age'].mean())

In [104]:
titanic['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [105]:
def change_flag(val):
    new_val = 0
    if(val == 'S'):
        new_val = 1
    elif(val == 'C'):
        new_val = 2
    elif(val == 'Q'):
        new_val = 3
    else:
        new_val = 0  
    return new_val
titanic['Embarked'] = titanic['Embarked'].apply(change_flag)

In [106]:
titanic['Embarked'] = titanic['Embarked'].fillna(value=titanic['Embarked'].mean())

In [107]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 8 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Sex         891 non-null object
Age         891 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Embarked    891 non-null int64
dtypes: float64(2), int64(5), object(1)
memory usage: 62.6+ KB


In [108]:
titanic.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare  Embarked
PassengerId                                                                 
1                   0       3    male  22.0      1      0   7.2500         1
2                   1       1  female  38.0      1      0  71.2833         2
3                   1       3  female  26.0      0      0   7.9250         1
4                   1       1  female  35.0      1      0  53.1000         1
5                   0       3    male  35.0      0      0   8.0500         1

In [109]:
titanic['Sex'] = titanic['Sex'].apply(lambda val: 0 if val=='male' else 1) #ToDo: 'enhance so that it can be run as many times as needed

In [110]:
titanic['Sex'].unique()

array([0, 1])

In [111]:
## lets play with Scikit-learn
#Split data
from sklearn.model_selection import train_test_split

In [9]:
?train_test_split

In [95]:
titanic.columns

Index(['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [113]:
y = titanic['Survived']

In [114]:
x = titanic.iloc[:,1:] #subselect using integer indices

In [116]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [112]:
X_train.shape

(1049, 3)

In [113]:
Y_train.shape

(1049, 1)

In [114]:
#create algorithm
from sklearn.linear_model import LogisticRegression

In [115]:
lr = LogisticRegression()

In [122]:
#Fit, Predict, score

In [122]:
#y = column_or_1d(Y_train, warn=True)
lr.fit(X_train, Y_train.ravel())

/Users/i331518/.local/share/virtualenvs/blog_post--c0N4EmN/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: Unknown label type: 'continuous'

In [125]:
y_preds = lr.predict(x_test)

In [126]:
y_preds

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1])

In [127]:
sum(y_preds==y_test)/len(y_test)

0.8044692737430168

In [129]:
from sklearn.metrics import classification_report

In [131]:
print(classification_report(y_pred=y_preds, y_true=y_test))

             precision    recall  f1-score   support

          0       0.82      0.86      0.84       105
          1       0.78      0.73      0.76        74

avg / total       0.80      0.80      0.80       179



In [132]:
from sklearn.metrics import confusion_matrix

In [136]:
confusion_matrix(y_pred=y_preds, y_true=y_test)

array([[90, 15],
       [20, 54]])

In [137]:
lr.score(x_test, y_test)

0.8044692737430168